name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: "curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash"
        shell: bash
      - name: Build
        run: anchor build
      - name: Run tests
        run: anchor test
